### PR TITLE
Bug Fixes, Refactor, and Enhancements

### PR DESCRIPTION
**Pull request by Martinez-Emmanuel**
Good day, FLSS team. This PR contains significant bug fixes and refactor across our whole system as we prepare for our testing phase soon. There are no new features, but these changes steer our existing system features into better reliability, usability, and maintainability. I will provide some screenshots for the changes visible in the UI but many of the changes lie under the hood aka _how it's done and how reliable they operate_. For a really complete detail of changes, just look at all the commits.

### Bug Fixes
---
**1. Fix the incorrect schedule validation across sections under a year level of a program.** I don't know if you've noticed this but there is a fatal flaw in our schedule validation, and that is it incorrectly checks the day and time schedule across ALL sections within a year level, which results in non-allowance of same day and time schedule for different sections. AKA if, for example, BSIT-TG Section 1 has a course "COMP 001" scheduled for Monday 07:30 AM to 12:30 AM, then no any course in BSIT-TG Section 2 can be scheduled at the same time - which is fatally wrong. We must allow the same day and time schedule as long as the faculty and room are different. So that means BSIT-TG Section 2 MUST be able to have a schedule for Monday 07:30 AM to 12:30 AM, _only if the faculty and room are different._ This bug has been around since October but I kept it quiet because it took me many attempts to fix it but the problem is very intricate that I had to rewrite our scheduling validation process from the start and I know some of you will overthink it a lot. 

pr1

pr2

**2. Fix the admin and faculty management.** In PR #79, I refactored our database to split the names column into `*_name` columns. This also required a refactor in the CRUD of our Faculty and Admin management which involves the addition of the new name fields in frontend and changes in our APIs for CRUD in the backend.

**3. Fix the sending of email and email details.** This is the bug I spent most of the time on. This required a major refactor in how we send the email for the opening of preferences submission. Before, the old process looks like this: In frontend, the admin toggles the preferences, checks the email checkbox. The frontend calls the `toggle-*-preferences` API, and upon success, the Angular makes another request to another API endpoint `email-*-preferences`. This violates many fundamental programming designs. It breaks atomicity principle because the toggling of preferences enabling is seperate from the email even though they should be a single transaction. It also introduces race conditions especially when the network is slow, and creates a tight coupling of the Angular component and the backend controller. Think when the sending of emails is done in production to all faculty in PUPT. At some point, the old design will break and become unusable. 

Aside from this, there are so many bugs such as the incorrect "days left" calculation (e.g. it shows -5.234234 days for example), and off by a few hours due to timezone problems (for example, sometimes it shows 8 days left even though it should really be 9 days, which is only noticeable if the UTC difference in Philippines and GMT crosses a certain point in the day, and that's why it's not normally a "noticeable" bug), the emails are also being sent IMMEDIATELY even if the toggle preferences is scheduled for the future,  emails being sent sometimes, and sometimes not (failing) and other shit ton of problems. Just look at the codes for more info.

Also I improved the UI of sending preferences since we are so close to testing phase. We'll just modify the message once the message template has been given to us.

image

**4. Fix the duplicate semester options for faculty schedule history.** Before, when fetching the faculty schedule history, the dropdown shows multiple similar semester options for EACH year level. So if a faculty had a schedule for Year Level 1, 2, and 4 for example, the dropdowns will be 1st Semester, 1st Semester, 1st Semester. Now it correctly shows the semester options.
image

**5. Fix reactivity in curriculum-detail.** This component was already significantly enhanced by @Malaluan-KylaRica in PR #82, but there are some areas that still needed to be improved such as:

- When first loading the component, (from `curriculum` → `curriculum-detail` through "View" button, it does not show the loading bar which can be confusing to the user especially if the network is slow. Now, a loading bar is added which improves perceived delay.
- The manage programs has noticeable delay when opening due to the nature of API calls. Now, a loading spinner is added.
- When selecting/unselecting a program, the UI does not update immediately which can cause confusion to the user especially if they are inside that selected program (for example, if user is inside the "DIT" program, clicks the Manage Programs button and unchecks/reemove DIT, the UI does not react to this change and a page reload is needed). Now the component reactively update when this happens.
- When the loading flag is introduced, the CRUD operation reloads the whole component. Now the component dynamically updates the table when adding/editing/deleting a course.
- Course code too short. Now both the frontend and backend consistently accept 50 max characters
- Year Level dropdowns not correctly resetting when changing a program. For example, if user has selected "BSIT-TG" "Year Level 4" and then selected "DIT-TG" (which only has 3 years), the dropdown goes blank and don't know what to do because it can't find the value for year 4. Now everytime a program is changed, we reset the year level selection to 1 for consistency.
- The "Laboratory Hours" field displays empty if the value received from backend is `0`. Now it displays `0` as is.

**6. Fix the programs schedules report missing some courses.** The schedule timeline in our `report-programs` component is buggy, as it incosistently displays missing schedules beyond year level 1. It displays schedules for some sections, but not to others. This is fixed now.

#### Other bug fixes:
- UI stutter when switching between slide toggle and scheduled button in `manage-preferences` component table
- Fix the logic for determining the "toggle all" logic which incorrectly disables the toggles
- Fix whitespaces in `dialog-toggle-preferences` due to conditional visibility of mat-hint
- Fix date conversion discrepancies in some components

### Enhancements
---
**1. Enhance the UI for scheduled preferences.** In PR #80, we added the feature to allow scheduled enabling of preferences submission. However it was still untuitive to use. There was no clear distinction if the preferences are disabled or scheduled. Now it shows a scheduled badge which quickly identifies if faculty are scheduled to open their submission or not.

In the table:
image

In the dialog:
image

**2. Reformat the dates to use MMMM, DD, YYYY format**. All our date fields have been converted to use this format.

image

image

**3. Make the text format in Preferred Day & Time more readable.** Before, the format was like this: 

`Day (Start Time - End Time), Day (Start Time - End Time), Day (Start Time - End Time), ...`

Now it's been reformatted too:

`Day (Start Time - End Time)`
`Day (Start Time - End Time)`
`Day (Start Time - End Time)`
`...`

image

### Code Improvements
---
**1. Migrate the `preferences` component to the modern Angular Signals approach.** Signals are one of the newest features introduced in recent Angular versions, and many of its APIs have become stable in version 19. Hence, I tried to migrate this component to fully embrace the signals approach to improve reactivity and app performance. If you encounter a bug in this component, let me know right away. 

**2. Improve modularity of our schedule-related components and services.** Before, our scheduling service contained a whopping 900+ lines of codes, mainly due to the extensive implementation of schedule validation. Now I created another service named `schedule-validation` that is decoupled from our main `scheduling` service which now has 1/3 length of its former version, which greatly improves the readability and maintainability for future development.

**3. Remove unused imports, methods, or API routes**
**4. Refactor many components particularly the dialogs for better performance and optimizations**

Overall, these changes make our system align with our clients' needs, make it more reliable, faster, more secure, etc. Also, this is a challenge to you to make the testing more thorough. While I was able to catch a lot of these issues, I am sure there are still several out there lurking and waiting to reveal itself at the worst possible time. The more bugs and issues you find, the better. It's better to catch these bugs here in development than there in front of a faculty during testing, our client, or the panelists. The system is big, complex, and all modules are interconnected. What you're doing in one module may work on the surface but think how it affects and propagates other parts of the system.

Unless there are changes, this will be my last PR related to our core system process for a while as I'll be focusing on our HRIS integration moving forwards. Happy holidays everyone.

### CODE REVIEW

**Comment by Malaluan-KylaRica** [comment]
Thank you for the enhancements, bug fixes, and for improving the components that needed attention. I have already finished reviewing the changes you've made to both the database and the frontend. I also appreciate the detailed explanations for each change in the PR. Thank you as well for checking the changes I made in the curriculum details and for fixing the bugs I missed while working on it. I will review everything thoroughly again after merging it into my local environment. Your effort and hard work in improving our system are greatly appreciated. Happy holidays to you too!

**Review by Rasquero-ViaClariz — COMMENTED** [review]
Amazing work on this PR! The fixes and updates make the system work better and easier to use. Thank you for the clear details and screenshots, they help a lot. I will test the changes and let you know if I find anything. Thanks for your hard work, and happy holidays!

**Review by Naoe-Adrian — APPROVED** [review]
Thanks for the effort to adjust the database, controller and the ui/ux this is a steps to achieve our objective in our capstone. Ill test this in my local machine once I accept this PR! LGTM

**Comment by Naoe-Adrian** [comment]
Thanks a lot @Martinez-Emmanuel while Im reading your PR Im amazed on the improvement you made from ui to logic to db. Happy holidays Take care guys

**Pull request merged**
